apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops
data:
  POSTGRES_DB: mlops_db
  MINIO_ENDPOINT: minio:9000
  MLFLOW_TRACKING_URI: http://mlflow:5000
  MLFLOW_S3_ENDPOINT_URL: http://minio:9000
  MLFLOW_S3_IGNORE_TLS: "true"
